import Head from 'next/head';
import { Inter } from 'next/font/google';
// import Image from 'next/image';
import { useState, useEffect } from 'react';
import axiosClient from '@/api/axiosClient';
import 'react-medium-image-zoom/dist/styles.css';
import Header from '@/components/Header';
import Image from 'next/image';
import Gallery from '@/components/Gallery';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Thumbs } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/thumbs';
import 'swiper/css/zoom';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [hasWindow, setHasWindow] = useState(false);
  const [imageList, setImageList] = useState<any>([]);
  const [isLoad, setIsLoad] = useState(false);
  const [showGallery, setShowGallery] = useState<boolean>(false);
  const [index, setIndex] = useState<number>();
  const [thumbsSwiper, setThumbsSwiper] = useState<any>();
  const [swiperIndex, setSwiperIndex] = useState<any>();

  useEffect(() => {
    const getList = async () => {
      try {
        const res = await axiosClient.get('/api/post');
        setImageList(res);
      } catch (error) {
        console.log(error);
      }
    };
    getList();
  }, [isLoad]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setHasWindow(true);
    }
  }, []);

  const handleClickImage = (index: number) => {
    setShowGallery(!showGallery);
    setIndex(index);
  };

  return (
    <div>
      <Head>
        <title>Sphoto</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header isLoad={isLoad} setIsLoad={setIsLoad} />
        <div className='columns-4 gap-[15px] p-[15px] bg-black'>
          {hasWindow &&
            imageList?.map((item: any, index: number) =>
              item.type === 'image' ? (
                <div
                  key={index}
                  onClick={() => handleClickImage(index)}
                  className='w-full mb-[15px] rounded-xl border-[#313131] border-[1px] overflow-hidden cursor-pointer'>
                  <Image src={item.url} alt='c' width={720} height={720} />
                </div>
              ) : (
                <div
                  key={index}
                  onClick={() => handleClickImage(index)}
                  className='mb-[15px] rounded-xl border-[#313131] border-[1px] overflow-hidden cursor-pointer'>
                  <video autoPlay loop muted controls className='w-auto h-auto'>
                    <source src={item.url} />
                  </video>
                </div>
              )
            )}
        </div>
        {showGallery ? (
          <Gallery
            imageList={imageList}
            showGallery={showGallery}
            setShowGallery={setShowGallery}
            index={index}
          />
        ) : (
          <></>
        )}
      </main>
    </div>
  );
}
