import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState, useEffect } from 'react';
import axiosClient from '@/api/axiosClient';
import Image from 'next/image';
import Gallery from '@/components/Gallery';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/thumbs';
import 'swiper/css/zoom';
import { useAppSelector } from '@/Redux/hooks';
import { FaRegImage } from 'react-icons/fa';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const user = useAppSelector((state) => state.user);
  const loading = useAppSelector((state) => state.loading.value);
  const [hasWindow, setHasWindow] = useState(false);
  const [postList, setPostList] = useState<any>([]);
  const [showGallery, setShowGallery] = useState<boolean>(false);
  const [index, setIndex] = useState<number>();

  useEffect(() => {
    const getList = async () => {
      try {
        const res = await axiosClient.get(`/api/post/${user._id}`);
        setPostList(res);
      } catch (error) {
        console.log(error);
      }
    };
    getList();
  }, [user._id, loading]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setHasWindow(true);
    }
  }, []);

  const handleClickImage = (index: number) => {
    setShowGallery(!showGallery);
    setIndex(index);
  };

  return (
    <div>
      <Head>
        <title>Sphoto</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='mt-[60px]'>
          {postList.length === 0 ? (
            <div className='flex justify-center items-center h-[100vh] bg-black text-[#aaaaaa]'>
              <div className='flex justify-center items-center w-[70%] h-[50%] border-2 border-[#A0A1A4] rounded-[6px] text-[30px]'>
                Create your gallery{' '}
                <FaRegImage className='ml-10 text-[100px]' />
              </div>
            </div>
          ) : (
            <div className='columns-4 gap-[15px] p-[15px] bg-black'>
              {hasWindow &&
                postList?.map((item: any, index: number) =>
                  item.type === 'image' ? (
                    <div
                      key={index}
                      onClick={() => handleClickImage(index)}
                      className='w-full mb-[15px] rounded-xl border-[#313131] border-[1px] overflow-hidden cursor-pointer'>
                      <Image src={item.url} alt='c' width={720} height={720} />
                    </div>
                  ) : (
                    <div
                      key={index}
                      onClick={() => handleClickImage(index)}
                      className='mb-[15px] rounded-xl border-[#313131] border-[1px] overflow-hidden cursor-pointer'>
                      <video
                        autoPlay
                        loop
                        muted
                        controls
                        className='w-auto h-auto'>
                        <source src={item.url} />
                      </video>
                    </div>
                  )
                )}
            </div>
          )}
          {showGallery ? (
            <Gallery
              postList={postList}
              showGallery={showGallery}
              setShowGallery={setShowGallery}
              index={index}
            />
          ) : (
            <></>
          )}
        </div>
      </main>
    </div>
  );
}
